import { UpdateAugmentAV, UpdateAugmentModuleCapacity } from "../../update functions/engineering/update-augmentation";
import { UpdateTotalAV } from "../../update functions/update-combat";

on("change:headAugmentAV", UpdateTotalAV);
on("change:leftEyeAugmentAV", UpdateTotalAV);
on("change:rightEyeAugmentAV", UpdateTotalAV);
on("change:torsoAugmentAV", UpdateTotalAV);
on("change:leftArmAugmentAV", UpdateTotalAV);
on("change:rightArmAugmentAV", UpdateTotalAV);
on("change:leftHandAugmentAV", UpdateTotalAV);
on("change:rightHandAugmentAV", UpdateTotalAV);
on("change:leftLegAugmentAV", UpdateTotalAV);
on("change:rightLegAugmentAV", UpdateTotalAV);
on("change:leftFootAugmentAV", UpdateTotalAV);
on("change:rightFootAugmentAV", UpdateTotalAV);

on("change:augmentations_head", UpdateAugmentAV);
on("change:augmentations_leftEye", UpdateAugmentAV);
on("change:augmentations_rightEye", UpdateAugmentAV);
on("change:augmentations_torso", UpdateAugmentAV);
on("change:augmentations_leftArm", UpdateAugmentAV);
on("change:augmentations_rightArm", UpdateAugmentAV);
on("change:augmentations_leftHand", UpdateAugmentAV);
on("change:augmentations_rightHand", UpdateAugmentAV);
on("change:augmentations_leftLeg", UpdateAugmentAV);
on("change:augmentations_rightLeg", UpdateAugmentAV);
on("change:augmentations_leftFoot", UpdateAugmentAV);
on("change:augmentations_rightFoot", UpdateAugmentAV);

on("change:augmentations_head_quality", UpdateAugmentAV);
on("change:augmentations_leftEye_quality", UpdateAugmentAV);
on("change:augmentations_rightEye_quality", UpdateAugmentAV);
on("change:augmentations_torso_quality", UpdateAugmentAV);
on("change:augmentations_leftArm_quality", UpdateAugmentAV);
on("change:augmentations_rightArm_quality", UpdateAugmentAV);
on("change:augmentations_leftHand_quality", UpdateAugmentAV);
on("change:augmentations_rightHand_quality", UpdateAugmentAV);
on("change:augmentations_leftLeg_quality", UpdateAugmentAV);
on("change:augmentations_rightLeg_quality", UpdateAugmentAV);
on("change:augmentations_leftFoot_quality", UpdateAugmentAV);
on("change:augmentations_rightFoot_quality", UpdateAugmentAV);

on("change:augmentations_head_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_jaw_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_leftEye_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_rightEye_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_torso_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_leftArm_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_rightArm_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_leftHand_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_rightHand_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_leftLeg_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_rightLeg_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_leftFoot_quality", UpdateAugmentModuleCapacity);
on("change:augmentations_rightFoot_quality", UpdateAugmentModuleCapacity);