import { UpdateArtillery, UpdateBow, UpdateBrawling, UpdateOneHandedMelee, UpdatePistol, UpdateRifle, UpdateShield, UpdateTwoHandedMelee } from "../update functions/skills/update-skills-combat";
import { UpdateAugmentation, UpdateAutomachinery, UpdateClockworkMechanics, UpdateGunsmithing, UpdateTinkering, UpdateVehicleMechanics } from "../update functions/skills/update-skills-engineering";
import { UpdateAstronomy, UpdateEconomy, UpdateHistory, UpdateLiterature, UpdateMedicine, UpdateMythology, UpdateNature, UpdateSurvival } from "../update functions/skills/update-skills-knowledge";
import { UpdateAlchemy, UpdatePrayer, UpdateRunecraft, UpdateSpellwork, UpdateSummoning } from "../update functions/skills/update-skills-magic";
import { UpdateArtisanship, UpdateAthletics, UpdatePerception, UpdatePiloting, UpdateStealth } from "../update functions/skills/update-skills-physical";
import { UpdateDeception, UpdateIntimidation, UpdatePerformance, UpdatePersuasion } from "../update functions/skills/update-skills-social";

// Event Listeners for Skill Rank changes
on("change:athletics", UpdateAthletics);
on("change:perception", UpdatePerception);
on("change:piloting", UpdatePiloting);
on("change:stealth", UpdateStealth);
on("change:artisanship", UpdateArtisanship);
on("change:deception", UpdateDeception);
on("change:intimidation", UpdateIntimidation);
on("change:performance", UpdatePerformance);
on("change:persuasion", UpdatePersuasion);
on("change:astronomy", UpdateAstronomy);
on("change:economy", UpdateEconomy);
on("change:history", UpdateHistory);
on("change:literature", UpdateLiterature);
on("change:medicine", UpdateMedicine);
on("change:mythology", UpdateMythology);
on("change:nature", UpdateNature);
on("change:survival", UpdateSurvival);
on("change:clockworkmechanics", UpdateClockworkMechanics);
on("change:automachinery", UpdateAutomachinery);
on("change:augmentation", UpdateAugmentation);
on("change:gunsmithing", UpdateGunsmithing);
on("change:tinkering", UpdateTinkering);
on("change:vehiclemechanics", UpdateVehicleMechanics);
on("change:alchemy", UpdateAlchemy);
on("change:prayer", UpdatePrayer);
on("change:spellwork", UpdateSpellwork);
on("change:runecraft", UpdateRunecraft);
on("change:summoning", UpdateSummoning);
on("change:artillery", UpdateArtillery);
on("change:brawling", UpdateBrawling);
on("change:bow", UpdateBow);
on("change:pistol", UpdatePistol);
on("change:rifle", UpdateRifle);
on("change:shield", UpdateShield);
on("change:onehandedmelee", UpdateOneHandedMelee);
on("change:twohandedmelee", UpdateTwoHandedMelee);